# Generated by Django 4.1.7 on 2023-04-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensepool',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='softwarepercomputer',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Price'),
        ),
    ]
