# Generated by Django 4.1.8 on 2023-05-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_licensepool_price_softwarepercomputer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolrequest',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Price'),
        ),
    ]
